### ISSUE TITLE
TanH fit

### ISSUE THREAD

**Issue by rslu** [psi46/pxar#248]
I pull from git again this morning for Urs update of initialize tanH for every pixels but the fits are not very good still.
I traced down to two issues.
- in code ana/PixInitFunc.cc
<pre>
158   f->SetParLimits(0, 1.e-3, 2.e-3);
</pre>
this bondary is too tight. lots of pixels hit 2e-3 boundary
which result bad fits.
Can we either remove this or set to much wider?
If I comment it out, fits are much more stable.

- secondly, not critical, in hte same code
<pre>
163  double middle = h->GetMaximum() - h->GetMinimum();
164  double step = h->GetMaximum() - middle; 
</pre>
These are basically constants for all pixels as max/min of histograms are always 260./0.
The more correct one will be like 
<pre>

   double hmax = h->GetBinContent(h->GetMaximumBin());
   double hmin = hmax;
   for(int ii=1; ii<=h->GetNbinsX(); ii++) 
     if(h->GetBinContent(ii)>0 && h->GetBinContent(ii)<hmin) hmin=h->GetBinContent(ii);
   double middle =  ( hmax - hmin )/2.;
   double step = hmax - middle; 
</pre>
But even without these, with 1st correction, the fits can be performed.

**Comment by simonspa** [comment]
@ursl @rslu any news on this? Still relevant?

**Comment by ursl** [comment]
At least the specific example provided is fitted reasonably with the error function out of the box. For chips with significant low-q non-linearities things will need to be reconsidered. The error function cannot  accommodate asymmetric saturation regimes for the low-q and the high-q region. The Weibull cdf does not do better, btw. 

Cheers,
--U.
