### ISSUE TITLE
cmake options - compiling errors under Windows

### ISSUE THREAD

**Issue by MDallOsso** [psi46/pxar#251]
Thanks to @bojanh Bojan Hiti, we saw that the option:
        -cmake -DBUILD_HVSUPPLY=Keithley2410 ..
is not portable at all under Windows.
(same for cmake -DBUILD_HVSUPPLY=Iseg ..)

This is the error:
```
  c:......\github\pxar_3.4_141031\devices\rs232.h(39): fatal error C1083: Cannot open include file: 'termios.h': No such file or directory [C:\
```

I took a look at the rs232.cc and rs232.hh and the problems seem to be:
- #include termios.h --> it is used only for struct termios oldPortSettings;  Is it still needed?
- #include sys/ioctlh
- #include unistd.h

for the last one I think we have to do:
#ifdef _WIN32
#include <Windows.h>
#else
#include <unistd.h>
#endif

----------------------------------------------------------

Instead, with cmake option  cmake -DBUILD_dummydtb=ON ..
I got this error:
```
  C:\...........\GitHub\pxar_3.4_141031\core\usb\USBInterface.h(25): fatal error C1083: Cannot open include file: 'ftd2xx.h': No such file or directory
```

are there any suggestions?
thanks
Martino

**Comment by ursl** [comment]
Hi all, 

what is the status of this? Are Windows machines not capable of compiling/running with a HV supply? 

If yes -- is this a limitation to anybody? Would whoever is affected by this volunteer to work on it? 

Cheers,
--U.

**Comment by sheindl** [comment]
Hi Urs.
I just checked with the latest pXar version and the problem @MDallOsso mentioned on December 10 is still there. termios.h is a POSIX header and therefore not available under Windows. Without power supply option building pXar is fine.
We at KIT have one Windows setup with a Keithley 2410 and there we control it via LabWindows (outside of pXar). Therefore we do not need power supply support under Windows at the moment. It would only be a "nice to have".

Cheers,
Stefan
