### ISSUE TITLE
Log file empty under Windows

### ISSUE THREAD

**Issue by bojanh** [psi46/pxar#255]
I am running pXar under Windows. After I run a test from console, the entire content of the log file is:
```
[15:07:26.514]     INFO: DUT info: 
[15:07:26.919]     INFO: enter 'restricted' command line mode
[15:07:26.919]     INFO: enter test to run
[15:07:28.666]     INFO:   test:  no parameter change
[15:07:28.838]     INFO: pXar: this is the end, my friend
```

When I run a test from GUI the output is even more compact:
<code>
[15:45:27.498]     INFO: DUT info: 
</code>.

I do however get an extra error message when I run from GUI:
<code>
cannot open ../phCalibrationFitTanH_C0.dat for reading PH calibration constants.
</code>
The measurement runs nevertheless fine and the root file is complete. So is the console output.

There seems to be a bug that suppresses the log file output under Windows. Does anyone have an idea how this can be overcome? 

Thanks, Bojan

**Comment by ursl** [comment]
if this issue is causing problems for any windows user, then please try to solve the issue on your windows  platform and let us know. Else we'll close the issue.

**Comment by MDallOsso** [comment]
I think it is not a huge issue, however it is fine to solve.
I will take a look at it even if I think it is not so straightforward to be fixed.
martino
