### ISSUE TITLE
Additional Histograms for X-Ray tests

### ISSUE THREAD

**Issue by MartinLip** [psi46/pxar#265]
Hello,

For the X-Ray qualification of the modules we have to do some tests in addition to the vcal calibration. In principle pxar provides everything that is necessary with the High Rate Efficiency test (xpixelalive) and  the xray/daq tests.
My opinion is that we do not want to upload raw hit data to the database, so pxar should create some additional histograms that can be analyzed by moreweb. It would be nice if someone was willing to implement these histograms in pxar.

Here is a list of possible outputs :

For the X-Ray test:
	- 1D Histogram: Number of total hits vs column number
	- 1D Histogram: Number of hits vs event number
	- 2D Histogram: Number of hits vs event number vs column number
	
For the HR Efficiency test:
	- 1D Histogram: Efficiency vs number of pixels

If you have further ideas, please let me know.
There should also be the possibility to measure S-Curves with X-Rays (all pixels enabled). Can the current  S-Curve test be used for this, or is there only the pixel under test enabled?

Greetings,

Martin

**Comment by ursl** [comment]
With commit f1dc0e0d5ffb02ccb217647e497cc75ed88558b2 there is now a method xNoiseMaps in the high-rate test. This runs a VCAL s curve, fits with an error function, and stores the usual maps (threshold position and width, aka noise, plus the "noise level") as thr, sig, and thn respectively. 

For me this works well with a single ROC, but with modules there are maybe issues (e.g.: despite Ntrig = 50 I still have very sharp thresholds for a few percent of the pixels). 

With the default parameters this requires a trimmed detector. Else you should increase the DAC range. Decreasing the VCAL DAC range to speed up things is likely risky. 

This subtest is closely related to the new capabilities of the DacScan (where all pixels can be enabled and tested). The difference is that this is part of the high-rate doTest() function (in case anybody is using that, if not then please let me know what should be changed to make it useful) and the analysis (s-curve fitting). 

I would suggest that for discussions on this new test, a new issue should be opened.
