### ISSUE TITLE
User Manual / Documentation

### ISSUE THREAD

**Issue by simonspa** [psi46/pxar#27]
We should starting to prepare some sort of user manual, a PDF that can be distributed which explains:
- [x] the API interface and the design decisions behind it.
- [ ] the test framework. This together with the above item should allow every potential developer/user to easily implement their own tests.
- [ ] the UI we provide with pxar, i.e. the GUI, configuration file framework etc.

**Comment by ursl** [comment]
see https://github.com/psi46/pxar/blob/master/main.pdf (still growing), LaTeX sources in a different repository
