### ISSUE TITLE
scurves Ntrig too low

### ISSUE THREAD

**Issue by vtavolar** [psi46/pxar#274]
The default testParameters generated with main/mkConfig have Ntrig for Scurves test set to 5, which is likely to be the cause of noise distribution like this 

![screen shot 2014-12-19 at 15 45 25](https://cloud.githubusercontent.com/assets/5130294/5505981/3834097c-8796-11e4-80cb-c6e59c97adec.png)

This value should be set to 50, like discussed also during the ROC cross-calibration exercise.

This is just for documentation, I will do the fix.

**Comment by vtavolar** [comment]
Hi all,

I see the same behaviour @drberry85 observed with 50 triggers:

[10:26:05.351]     INFO: ######################################################################
[10:26:05.351]     INFO: PixTestScurves::doTest() ntrig = 50
[10:26:05.351]     INFO: ######################################################################
[10:26:05.351]     INFO: adjusting VCAL to have VthrComp average threshold at default VthrComp
[10:26:08.713]     INFO: Test took 3358ms.
[10:26:27.680]     INFO: Test took 18938ms.
[10:26:28.040]     INFO: ---> dac: VthrComp name: scurveVthrComp ntrig: 50 dacrange: 0 .. 250 hits flags = 16 (plus default)
[10:42:14.643] CRITICAL: <hal.cc/MultiRocAllPixelsDacScan:L908> Incomplete DAQ data readout! Missing 27389149 Events.
[10:59:43.308] CRITICAL: <hal.cc/MultiRocAllPixelsDacScan:L908> Incomplete DAQ data readout! Missing 27388550 Events.

I am using fw 3.6.
Still, 5 triggers are too few to have successful fits. Any ideas about how to solve this?

**Comment by ursl** [comment]
Hi Vittorio,

there seem to be two possibilities:

1) fix the readout errors (this is likely outside of pxar/core/test code)
2) go back to ntrig=5 and repeat those measurements where the fit is
problematic.

Sorry for not having a silver bullet.

Cheers,
--U.

**Comment by vtavolar** [comment]
Hi Urs,

thanks for your reply.

According to what you already posted https://indico.cern.ch/event/329374/contribution/1/material/slides/0.pdf 
ntrig=20 still leads to an underestimation of the noise, so I don't think that repeating measurements at ntrig=5 would help.

Just a naive idea:
is it possible to force pxar core to readout the DTB more often? Kind of de-parallelize the readout just for this test?

Vittorio

**Comment by drberry85** [comment]
Vittorio,

So what we do here at FNAL is we run the SCurve with 5 triggers to see
where the turn on happens in Vcal and then we run again with a restricted
Vcal range and a larger number of triggers.

-- Scurves
adjustvcal          checkbox(1)
Ntrig               100
DAC                 Vcal
DacLo               15
DacHi               55
scurves             button

It's not a permanent fix, but it allows you to do proper noise measurements.
Doug

**Comment by ursl** [comment]
Hi all,

I pushed an update of this this afternoon. In the scurves tab, there
is now a new parameter dacs/step. If set to <0, no change wrt to
previous code. By default, however, it is set to 10 and will split a
large DAC scan into steps of 10.

It would be helpful if you could test this with your modules, please.

It will take time, but presently I very much prefer a reproducible
slow test over something else.

Please re-open if it does not work for you.

Many thanks.

Cheers,
--U.
