### ISSUE TITLE
DAC label and enty fields misaligned

### ISSUE THREAD

**Issue by werdmann** [psi46/pxar#282]
The DAC labels in the hardware tab are misaligned on my screen.
ubuntu 14.02,   screen 1280 x 800

**Comment by werdmann** [comment]
forgot to attach the screenshot, here it comes
![pxar-screenshot](https://cloud.githubusercontent.com/assets/4669785/5736706/61630652-9bd9-11e4-9b00-93a1f3d917a1.png)

**Comment by werdmann** [comment]
and the "Save TBM Paramters" button is almost inaccessible on my tiny laptop screen.
![screenshot from 2015-01-14 16 07 51](https://cloud.githubusercontent.com/assets/4669785/5740862/aa4121c8-9c07-11e4-9406-1c36de736571.png)

**Comment by ursl** [comment]
I wanted to test myself on my VB, but you might as well pull and re-compile.

**Comment by werdmann** [comment]
Thanks Urs, much better.
The "Save" button still (almost) disappears at the bottom of my screen.

**Comment by ursl** [comment]
Hi Wolfram,

so I fiddled a bit with the appearance, but I have to admit that in my
virtual box with 1200x800 I have no problems to see everything. I
moved the save button (for the TBM) up, for the time being. This area
will change in the future anyways.

If you still have problems, then I think your fonts need fine-tuning.
You could start by putting something like

Gui.DefaultFont:            -adobe-helvetica-medium-r-*-*-18-*-*-*-*-*-iso8859-1
Gui.MenuFont:               -adobe-helvetica-medium-r-*-*-18-*-*-*-*-*-iso8859-1
Gui.MenuHiFont:             -adobe-helvetica-bold-r-*-*-18-*-*-*-*-*-iso8859-1
Gui.DocFixedFont:           -adobe-courier-medium-r-*-*-18-*-*-*-*-*-iso8859-1
Gui.DocPropFont:            -adobe-helvetica-medium-r-*-*-18-*-*-*-*-*-iso8859-1
Gui.IconFont:               -adobe-helvetica-medium-r-*-*-18-*-*-*-*-*-iso8859-1
Gui.StatusFont:             -adobe-helvetica-medium-r-*-*-18-*-*-*-*-*-iso8859-1

into your ~/.rootrc file. This should at least show an effect. 18 is
most likely way to big.

Cheers,
--U.
