### ISSUE TITLE
Timing test for TBM09?

### ISSUE THREAD

**Issue by ursl** [psi46/pxar#285]
Hi all, 

is the timing test capable of dealing with TBM09? I can run it w/o problems (mostly...) for TBM08(b), but with a TBM09 I reproducibly get a bad crash: 

[11:44:06.702]     INFO: SDA delay found at clock:4
[11:44:06.702]     INFO: clk:    4
[11:44:06.702]     INFO: ctr:    4
[11:44:06.702]     INFO: sda:    10
[11:44:06.702]     INFO: tin:    9
[11:44:06.788]     INFO: Test took 13516 ms.
[11:44:06.788]     INFO: PixTestTiming::ClkSdaScan() done.
[11:44:06.819]     INFO:    ----------------------------------------------------------------------
[11:44:06.819]     INFO:    PixTestTiming::PhaseScan()
[11:44:06.819]     INFO:    ----------------------------------------------------------------------
[11:44:06.893]  WARNING: Pattern generator contains TBM Reset signal. No event number cross checks possible.
libc++abi.dylib: terminate called throwing an exception

The stack trace does not look particularly helpful, I think. 

I did specify to mkConfig -t tbm09.

Am I the only one to observe this or am I missing something?

**Comment by simonspa** [comment]
Can you maybe run with some debugger tool to get a more meaningful output? The only thing this trace says is it crashes in some osx system libraries.

Also running the test with a higher debug level might help gathering information.

I don't have a TBM09 around to test myself.

**Comment by ursl** [comment]
Eventually I will try to look into this a bit more. As the code itself
warns about TBM09, I will first try to understand how to setup TBM08b to
have working setups. For me, the timing test is unfortunately not really
delivering a stable working point w/o readout errors.

Cheers,
--U.

**Comment by simonspa** [comment]
Which code warns about the TBM09? The timing test or some of the DAQ routines?

**Comment by ursl** [comment]
The timing test! I can run e.g. PixelAlive and the Pretest w/o problems on
the module with the TBM09. I am not aware of a problem in core regading
TBM09. The line I was referring to is

https://github.com/psi46/pxar/blob/master/tests/PixTestTiming.cc#L240

I wanted to try the timing test because as soon as I go to more "expensive"
readouts I am flooded with r/o errors in the TBM09 module.

The purpose of my initial posting was just to see whether I am the only one
to experience this problem.

Cheers,
--U.

**Comment by simonspa** [comment]
The question is if we can't rewrite the timing test a little using the internal pxarCore decoding routines instead of replicating them. With the error reporting merged we could request single decoded events and then immediately check for errors and their type via `pxarCore::getStatistics()`.

Not sure that would work out in the current state, maybe @drberry85 has some insight here.

Am 21. Januar 2015 11:50:12 MEZ, schrieb Urs Langenegger <notifications@github.com>:

**Comment by ursl** [comment]
I had readout problems in the past week for two reasons: 
- wrong TBM phase (this is cured, in particular for the TBM09, with the recipe below; for the TBM08B you should first try PixTestTiming)
- degraded digital voltage when operating 16 pixels near their noise limit

The manual recipe: 
- likely increase VD to e.g. 2.8 to 2.9 (this is now done by default in mkConfig)
- do a scan: 
   chose one specific 160MHz setting

   choose one specific ROC port delay (identical for both ports)

   scan the 400MHz clock (e.g. basea = 0x64 and basee = 0x20 .. 0x3c in steps of 4).

- do the scan without the GUI (for convenience and for being sure that the TBM is reset [missing feature in the GUI]): 

    ../bin/pXar -d D14-0010-0011 -v DEBUGHAL -t PixelAlive:alivetest -p "ntrig=1000"
   
    ../bin/pXar -d D14-0010-0011 -v DEBUGHAL -t dacdacscan

    i.e. edit tbmParameters_C0?.dat manually between scan points.
   (You may have to interrupt the "endless" printout if your phase settings are bad; alternatively you could run with less than DEBUGHAL)

You can also try to run without increasing VD. If you then have problems when running a VthrComp scan to the noise limit (e.g. in the pretest or in the dacdacscan), the first thing to try is to increase VD (imvho) or alternatively reduce the VthrComp range (but that's not an option in the FullTests).

If the above is unclear, have a look at Wolfram's slides in https://indico.cern.ch/event/357381/

I cannot run the TBM09 module without any readout errors at the moment, but they are quite rare and (mostly) "only" decoding errors and therefore not really fatal and I have not really tried to find the best possible phase settings (it was sufficient for me to have three consecutive FullTests run completely and successfully to the end). 

There will be a short/minimal automatic TBM phase setup somewhere in the (not too distant) future.

**Comment by ursl** [comment]
Hi all, 

Vittorio pointed out that the original link to Wolfram's information is in a protected meeting. Sorry, I had not noticed. Please try 

https://indico.cern.ch/event/363732/material/0/0.pdf

instead (this is the normal agenda of last week's pxar meeting, where Wolfram's pdf is added as a document). 

Cheers,
--U.
