### ISSUE TITLE
HighRate test: memory footprint increasing linearly with time 

### ISSUE THREAD

**Issue by ursl** [psi46/pxar#286]
Hi Simon, 

I observe that running the high-rate test for a long while leads to a large resident memory footprint (2.5GB after 15 minutes with a low-rate x-ray source). 

This "memory leak" is very much reduced by adding to pxarCore::daqGetEventBuffer() the line

  for(std::vector<Event*>::iterator it = buffer.begin(); it != buffer.end(); ++it) { delete *it; }

before "return data", i.e. before https://github.com/psi46/pxar/blob/master/core/api/api.cc#L1295.

Cheers,
--U.

**Comment by simonspa** [comment]
Hi Urs,

I'm in a meeting, so will only check later, but this might actually be a nice catch. I have to rethink how and where I free that memory.

You still get all the correct data out, right, even with that line?

Am 21. Januar 2015 11:34:39 MEZ, schrieb Urs Langenegger <notifications@github.com>:

**Comment by ursl** [comment]
Yes, I get the correct data. It's copied into data and returned there, if I
am not mistaken. I have tested/seen this only on a mac, not tried (yet) to
replicate this on another system.

Cheers,
--U.
