### ISSUE TITLE
triggerdelay setting not working in HighRate test

### ISSUE THREAD

**Issue by rslu** [psi46/pxar#290]
While I was running HighRate test, I experienced that setting
triggerdelay in the HighRateTest has no effect.
Only setting it in the tbParameters.dat I see the famous chopping TBM readout effect disappearing.

**Comment by ursl** [comment]
can you please try again with https://github.com/psi46/pxar/commit/6d800d407a1e7fbe627f60c32f650f58c19b79d9?

The triggerdelay setting was only 'active' in runDaq, not in xpixelalive. This is a bug. 

(I am currently not at PSI, so I cannot test myself quickly).

**Comment by rslu** [comment]
It works now.

**Comment by jking79** [comment]
rslu,
Should have checked my email sooner, I was busy working those results up for you.  Would have had them sooner, unfortunately I am not in the lab on Tuesdays or Thursdays except for a couple of hours.  
Jack 

     On Thursday, February 5, 2015 5:07 AM, Urs Langenegger <notifications@github.com> wrote:
   

 can you please try again with 6d800d4?The triggerdelay setting was only 'active' in runDaq, not in xpixelalive. This is a bug. (I am currently not at PSI, so I cannot test myself quickly). —
