### ISSUE TITLE
fallback for missing trimmed config files

### ISSUE THREAD

**Issue by jhoss** [psi46/pxar#291]
Dear all,
today I noticed that when pxar ist started with -T 40 (where 40 of course can be any trim value) with no dacParameter40_C0.dat and trimParameter40_C0.dat files present in the test folder, we cannot work with the sample. Apperently empty files are used for the input parameters and thus the sample is in a state where we cannot operate it.
I would suggest, that in such a case where the trimmed dac and trimParameter files are missing, the non-trimmed ones (dacParameters_C0.dat and trimParameters_C0.dat) are used to start up the sample. Of course the user should be informed about this with a warning message.

This request has the following background:
When we use elComandante for Xray testing the modules we typically run through the following test sequence: Pretest>Trim>PhOptimization>GainPedestal>several_Xray_tests
In this chain we don't have trimmed config files for the sample when starting the Pretest. However we need to start pxar using the trimmed config parameters for PhOptimization,GainPedestal and the Xray tests. Currently this is not possible since elComandante takes the -T option for pxar for the whole test chain or not at all. With the request above we could start pxar in this test chain with the -T option and for the Pretest where there are no trimmed configs we safely fall back to the standard trim and dacParameters.

**Comment by ursl** [comment]
Hi Jan, 

https://github.com/psi46/pxar/commit/851126969beb88340ea6627d8762bbab74f24767 should fix this. Please reopen if it does not. 

Cheers,
--U.
