### ISSUE TITLE
Save hotpixel mask in a file

### ISSUE THREAD

**Issue by piberger** [psi46/pxar#294]
I would like to have a way to export the hotpixel map from the xray test to a file, eg. a "maskFile.dat" with the same format as the "defaultMaskFile.dat", which then is/can be loaded when starting pXar. 
This would allow to do first a hotpixel mapping (with xray off) and then the xray clibration with spectrum (xray on) with elComandante.

**Comment by ursl** [comment]
Hi Pirmin, 

https://github.com/psi46/pxar/commit/7a0698556cf56f9e043a423c4af5b3f21620d97a should add this feature. 

Note that a maskfile name of "default" will not change the name of the maskfile. If you change it to something else, that something else will be taken. 

By default the maskfile saving is turned off to retain the previous behavior. If others want this as well, this default can be changed. 

The same functionality has been added to the highrate test. 

Please reopen if there are issues with the implementation. 

Cheers,
--U.

PS: You'll need to get the new testParameters.dat from mkConfig to see the changes in the GUI.
