### ISSUE TITLE
PixTest-fProblem variable always false in BareModule test

### ISSUE THREAD

**Issue by MDallOsso** [psi46/pxar#295]
bool fProblem variable is always false when read in ln245 of PixTestBareModule.
i.e. when a ROC is not programmable, fProblem becomes 'true' inside Pretest but it results 'false' when read inside PixTestBareModule.

Martino

**Comment by ursl** [comment]
Hi Martino,

fProblem is a data member of PixTest. If you call another PixTestX from PixTestBareModule, then PixTestBareModule::fProblem will NEVER be set if PixTestX has a problem. You could change PixTestBareModule::doStdTest() such that it returns the value of PixTestX::fProblem. 

Cheers,
--U.

**Comment by MDallOsso** [comment]
Urs, Thank you.
Now it is working. I will commit this later.

Martino
