### ISSUE TITLE
HV Support: add control of Voltage

### ISSUE THREAD

**Issue by simonspa** [psi46/pxar#296]
In case pxar is compiled with HV Supply support (either Keithley or Iseg, doesn't matter) it would be nice to also toggle the HV Supply when the HV ON/OFF button is hit.

In addition one should then add a configuration parameter "hv_voltage" or similar and put it on the H/W tab and in the config files.

This would allow real operation of the HV supply in all tests, not only in the HV tests. The call to turn the HV on/off can be guarded using
```
#ifdef BUILD_HV
...
#endif
```

**Comment by ursl** [comment]
Hi Simon, 

why is the relais operation on the DTB not sufficient?

Cheers,
--U.

**Comment by simonspa** [comment]
Well, why do we build in HV supply control if we then don't use it but still have to do it by hand? Only for the IV test? Imho it makes sense to use this also in that case (code to be added should be failry small)

**Comment by ursl** [comment]
You have to turn on the HV supply anyway by hand.
The button is used at the moment for the baremodule test, but there
switching off the relais is sufficient (I think).
Iirc, the HV button's existence was questioned in the past.

Maybe we can discuss this tomorrow.

Cheers,
--U.

**Comment by frmeier** [comment]
I can thinks of some use cases for this. Using it one can make sure to select the correct voltage and can keep it in a log file for documentation purposes. So I wouldn't fundamentally be against this option. I agree, somebody has to power up the HV supply but you also need to set the voltage by hand and having the software doing it as defined in some config would be handy. I see primarily the potential in automation and documentation.

Just my 2 cents.

**Comment by lantone** [comment]
Not to hijack the thread, but have any of you successfully used the HV supply functionality on Mac OSX?  I have some specific questions.  Possibly we could discuss at tomorrow's meeting, or otherwise maybe you could point me to the appropriate forum.  

Thanks, Jamie

**Comment by frmeier** [comment]
@lantone : Try to get in touch with @cfangmeier . We are using it on a Mac all the time.

**Comment by ursl** [comment]
ah, but now the request already includes setting the HV value as well?
Why not add coldbox steering as well? I would argue that elcomandante
is taking care of the automation (and the corresponding
documentation).

I am also not against this proposal "in principle", but I'd like to
see a solid use case. Not just "aesthetical"/design arguments.

I would in fact consider it an important safety aspect that a real
person turns on the HV supply and makes sure that the output is
correct/safe (for instance, would a polarity check be considered
essential as well?). Furthermore, I see potential issues when running
multiple pxar instances in the context of a coldbox fulltest.

By default, ONE pxar instance should control ONE DTB and the attached
(downstream) hardware, nothing more (and certainly not the generic
environment). Anything else needs a very good justification (e.g. IV
test, baremodule test. I am convinced that sooner or later we'll add
multiple DTB operation to pXar to accomodate linked DTB for beam tests
-- but that will be a reaction to a *real* need.)

Cheers,
--U.

**Comment by frmeier** [comment]
I don't want to be too much involved. My comments were not a request and if ElCommandante or other approaches are the recommended and more suitable way, no problem with me. All I wanted to say is that I can think of use cases in support of @simonspa and setting a voltage on an already connected HV power supply and turning it on are simple commands to be sent, likely ~2 lines of code. But others have to judge. Very likely I won't be a user for that feature anyway. Tf. I'm shutting up now ;).

**Comment by simonspa** [comment]
@ursl thank you for your very helpful sarcasm. Also thank you for once more pulling the "design is bad" card in response to a functionality request.

I'm also not sure what you mean by "add multiple DTB operation to pXar". We already recorded 100M triggers in test beam using two DTBs. Since I will never rely on any part of pXar GUI/tests there is no need to "accommodate" anything. Test beam just runs fine with `cmake -DBUILD_pxarui=OFF ..`.

Cheers.
