### ISSUE TITLE
HighRate: xpixelalive, trigger frequency setting in gui has no effect

### ISSUE THREAD

**Issue by piberger** [psi46/pxar#297]
(maybe related to #290)

In the gui in the HighRate tab, the "trgfrequency(khz)" setting in xpixelalive section has no effect, instead delay seems to be taken from "triggerdelay" setting in rundaq section.

**Comment by ursl** [comment]
I am not sure I understand your point. Do you want to set the trigger
frequency for the xpixelalive test? The triggerdelay parameter input mask
always maps onto the same data member, irrespective of its placement in the
GUI. So you could argue that the GUI placement of triggerdelay and
trgfrequency should be swapped, but as I said I'm not sure this is what you
said.

**Comment by piberger** [comment]
Yes, i wanted to set the trigger frequency for xpixelalive and see how it influences the efficiency. For this purpose i tried to change "trgfrequency(khz)" first, but did not see any changes in the result or in the time the test took and could not find any place in code where this setting is used. Maybe I missed something here.

**Comment by ursl** [comment]
No, you don't miss anything. So far the trigger rate was not changed for
the xpixelalive measurement. The reason is that this is done with a
pxarCore::getEfficiencyMap(...).

Cheers,
--U.

**Comment by simonspa** [comment]
You could still change the freuqency by altering the PG used. Note however, that there are additional delays in the NIOS code (also just from its actual execution) so that the real frequency will neither be stable over time (but come in bunches of ntrig) nor exactly the delay you set in the PG.

**Comment by piberger** [comment]
Ok, thanks both of you for the explanations. I would then suggest to remove the "trgfrequency(khz)" from the gui to avoid confusion, or move it if it is used in another subtest.

**Comment by piberger** [comment]
Ok, thanks both of you for the explanations. I would then suggest to remove the "trgfrequency(khz)" from the gui to avoid confusion, or move it if it is used in another subtest.

**Comment by ursl** [comment]
I think b3d21e4fa860f02565cb10df1f7bca3d9c456cdf should address this. The trigger frequency does have an effect (or it should, at least) for the runDaq test.
