### ISSUE TITLE
Request: option for CalDelScan to save dacs

### ISSUE THREAD

**Issue by piberger** [psi46/pxar#298]
I would like to have an option for CalDelScan to save the dacs to file (for use in later parts of the elComandante test chain).

**Comment by ursl** [comment]
Does pressing the SaveDacs button in the h/w tab not suffice?

**Comment by piberger** [comment]
Can you also do this with elComandante? In case it is possible to push the button with elComandante this would do the job.

**Comment by ursl** [comment]
I don't know how elcomandante talks to pxar. If you have a pipe, then you
could "savedacs" after
https://github.com/psi46/pxar/commit/a032308d2e39b6e2fd19ca0cc0f6cf1c9e7e8bf0
.

Cheers,
--U.

**Comment by piberger** [comment]
Thanks, it works and looks more elegant than what i suggested as it can be used for other tests too.
