### ISSUE TITLE
Pulse height map

### ISSUE THREAD

**Issue by thweiler** [psi46/pxar#300]
Hi
I observed some strange effect in the pulse height map test (pxar/usertest/PixTestMapPh.cc)
Not all ROCs respond with similar pulse height or do not respond at all (see attached plots). 
PixelAlive is looks good for all ROCs. Using getEfficiencyMap instead of getPulseheightMap
gives the same response for all ROCs. Has anybody an idea what is going wrong?

cheers
Thomas

M4507:
![m4507_mapph_vcal](https://cloud.githubusercontent.com/assets/7323782/6185853/5f343d22-b373-11e4-99eb-e6196b5c2ac7.png)
M4510:
![m4510_mapph](https://cloud.githubusercontent.com/assets/7323782/6185862/6ae40e40-b373-11e4-95e4-bd4ede7c73e7.png)
M4513:
![m4513_mapph](https://cloud.githubusercontent.com/assets/7323782/6185867/76cc9150-b373-11e4-85b5-9df4f0e17f7a.png)

**Comment by rslu** [comment]
I suppose you have run through either full test or at least phoptimization?
I would guess your PHOptimization failed and give the ROCs bad phscale and phoffset.
You can compare the DACs among ROCs or use one set for all and see the response.

**Comment by thweiler** [comment]
I did it after pre- and pixelalive test. Since in pixel alive all pixel see a signal I would expect the 
same for the pulse height. Vcal and VthrComp was the same as for the pixelalive test.

**Comment by simonspa** [comment]
@thweiler well, VCal and VthrComp are nice and need to be correct - but if your phoffset and phscale are off you will just have e.g. underflows in your pulseheights - creating those flat areas of `0` everywhere. As @rslu said, you also need to optimize those DACs to make sure you are in the working range of the ADC.

**Comment by simonspa** [comment]
One additions: pixel alive only checks if the pixel responds. The pulse height can still be zero - this is a valid measurement of the chip, just the ADC range was in underflow.

**Comment by thweiler** [comment]
OK thanks, I will close the issue here.
