### ISSUE TITLE
api::getEfficiencyMap(..) vs api::getEfficiencyVsDAC(..) with FLAG_CHECK_ORDER set

### ISSUE THREAD

**Issue by ursl** [psi46/pxar#307]
Hi Simon, 

it seems that a (VCAL) scurve with the complete ROCs enabled is considered desirable;  cf https://twiki.cern.ch/twiki/pub/CMS/BPixX-rayCalibration/GeneralSummary.rtf and also https://github.com/psi46/pxar/issues/265.

I think that its implementation (separating background hits from CAL hits) is not quite straightforward at the moment, as pxarCore::repackDacScanData  does not consider out-of-order (i.e. background xray) hits, which is done in  pxarCore::repackMapData.

I think there are two possibilities: 
1) Do the scan using api::getEfficiencyMap(), manually looping over a range of VCAL
2) Modification of pxarCore::repackDacScanData(..) to accomodate background xray hits (similar to pxarCore::repackMapData). 

What is your opinion? 

Cheers,
--U.

**Comment by simonspa** [comment]
Hej @ursl 

definitively 2) since 1) will produce a large overhead and lead to long test running time. Just give me a few minutes... :)

/Simon

**Comment by ursl** [comment]
Hi Simon, 

I don't think it's *hyperurgent*, given that DPG is going on. Next week is fine (for me at least)

Cheers,
--U.
