### ISSUE TITLE
Fix FLAG_CHECK_ORDER for single pixel runs

### ISSUE THREAD

**Issue by simonspa** [psi46/pxar#308]
As noted in 5fc5ebfc14269e678896156b877c1216f8032d38 the current implementation of FLAG_CHECK_ORDER processing has a bug. It currently only works if we really expect maps from a full device (aka all pixels tested). For single pixel runs it will fail miserably and flag the test pixel as out-of-order.
Make FLAG_CHECK_ORDER aware of what we are dealing with.

NB: move checking into separate function, pass list of expected pixels to repackData functions or similar.

**Comment by simonspa** [comment]
I'm a bit tempted to not fix this, also since it would require quite some changes. And: if I request data for a single pixel I already have the answer which pixel should be in data afterwards.

Opinion?

**Comment by ursl** [comment]
If I understand correctly then this is a non-issue. FLAG_CHECK_ORDER is (so far) needed for xray hit measurements with a fully enabled detector and for the address decoding test. I think both do not fall into the problematic category.
