### ISSUE TITLE
Save maskfile after hotpixel map

### ISSUE THREAD

**Issue by mcentis** [psi46/pxar#309]
Hello,
in the x-ray test meeting emerged the desire to save the maskfile produced during the hotpixel map so that the masking can be reused without the need to perform the test again.
Would it possible to add this feature?

Cheers
Matteo

**Comment by ursl** [comment]
Hi Matteo, 

this should be possible already. In PixTestHighRate there is a parameter fParSaveMaskedPixels (corresponding to a button) that will save the maskfile. Please see https://github.com/psi46/pxar/issues/294. If you do not have in your GUI, then please update the testParameters.dat file and make sure that you have the proper corresponding s/w. 

If I misunderstood your request, please explain it a bit better. 

Cheers,
--U.

**Comment by mcentis** [comment]
Hi Urs,
yes, that was the issue, i'll modify the testParameter file.

Thanks
Matteo
