### ISSUE TITLE
Segmentation fault in Xray test tab

### ISSUE THREAD

**Issue by piberger** [psi46/pxar#312]
In the Xray tab, a segfault can occur if phrun is executed after clearing the histograms. #311 should fix this.

    [19:18:00.710]     INFO: data taking finished, elapsed time: 5 seconds.
    [19:18:00.711]    DEBUG: <PixTestXray.cc/doPhRun:L410> after daqStop()
    [19:18:00.724]    DEBUG: <PixTestXray.cc/processData:L730> Getting Event Buffer
    [19:18:03.235]    DEBUG: <PixTestXray.cc/processData:L745> Processing Data: 492927 events.

     *** Break *** segmentation violation
    ===========================================================
    There was a crash.
    This is the entire stack trace of all threads:
    ===========================================================
    ...
    The lines below might hint at the cause of the crash.
    If they do not help you then please submit a bug report at
    http://root.cern.ch/bugs. Please post the ENTIRE stack trace
    from above as an attachment in addition to anything else
    that might help us fixing this issue.
    ===========================================================
    #6  0x00007f2593f05a9e in PixTestXray::processData (this=0x7f2590c5b010, numevents=<value optimized out>) at /home/pberger/pxar/tests/PixTestXray.cc:764
    #7  0x00007f2593f07e4f in PixTestXray::doPhRun (this=0x7f2590c5b010) at /home/pberger/pxar/tests/PixTestXray.cc:411
    #8  0x00007f2593f0a26c in PixTestXray::runCommand (this=0x7f2590c5b010, command="phrun") at /home/pberger/pxar/tests/PixTestXray.cc:123
    #9  0x00007f259396d898 in PixTab::buttonClicked (this=0x31e29e0) at /home/pberger/pxar/gui/PixTab.cc:305
    ===========================================================

**Comment by ursl** [comment]
the PR fixing this is in
