### ISSUE TITLE
dac scan extension

### ISSUE THREAD

**Issue by ursl** [psi46/pxar#322]
provide checkboxes for
- all pixels 
- unmasked ROCs

**Comment by ursl** [comment]
Item 1 is provided with commit https://github.com/psi46/pxar/commit/3353e7eda9e68db780985f6ac2ac6890c6a1d28e

Item 2 depends on issue #329

**Comment by simonspa** [comment]
Issue #329 is fixed, so I guess this one is also resolved?

**Comment by ursl** [comment]
Yes. It works well for a single ROC, not so sure yet about module (but maybe that is simply getting a bit warm).
