### ISSUE TITLE
Log for address decoding test does not match root output

### ISSUE THREAD

**Issue by jstupak** [psi46/pxar#334]
I ran the PixelAlive test, and in the log output I see:

[11:23:41.392] <TB0>     INFO:    ----------------------------------------------------------------------
[11:23:41.392] <TB0>     INFO:    PixTestAlive::addressDecodingTest() ntrig = 10, vcal = 200 (ctrlreg = 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
[11:23:41.392] <TB0>     INFO:    ----------------------------------------------------------------------
[11:23:44.705] <TB0>     INFO: Test took 3311ms.
[11:23:44.732] <TB0>     INFO: Fetched DAQ statistics. Counters are being reset now.
[11:23:44.978] <TB0>     INFO: PixTestAlive::addressDecodingTest() done
[11:23:44.978] <TB0>     INFO: number of address-decoding pixels (per ROC):     0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
[11:23:44.979] <TB0>     INFO: PixTestAlive::doTest() done, duration: 9 seconds

However, I get the attached TH2 in the root output.  So the log looks wrong.

My guess is that this is due to the inconsistency on lines 285 and 290 in PixTestAlive.cc.  Line 285 checks if the bin content is <0, while line 290 checks if it is <=0.  So if the bin content was exactly 0, it would not be counted as bad, but would show up as bad in the root file.

![addressdecodingtest_c7_v0](https://cloud.githubusercontent.com/assets/4885475/7384512/2bf43676-edfa-11e4-806c-b89cd0a275b0.png)

**Comment by ursl** [comment]
Is this a dead pixel?

If yes, would you then also count it as an address-decoding error? If
the answer is "yes", would you conclude similarly for the mask test
(which has much stricter implications)? Imho, a dead pixel is a dead
pixel and should not count towards address or mask defects (as it will
not deteriorate the performance in the sense of those defects).

We once had a three-state display for the address decoding (and mask
defect) histograms, showing -1, 0, and +1 to show the difference
between bad, dead, and good pixels. This was considered not good. So
now we are at a binary display.

The text output is not restricted by this limitation.

It's not clear to me this is a bug.

But it all rests on the question whether your blank pixel is dead or not.

Cheers,
--U.

**Comment by jstupak** [comment]
Hello Urs,

These pixels are indeed dead.  I understand your logic that these unaddressable and dead pixels should only be counted as dead and not also be counted as unaddressable.  But then I still argue there is an inconsistency between the log and the root output.  If we are not counting these pixels as unaddressable, why don’t they show up as red on the plots?  This is quite confusing..

From your explanation, I understand that if a pixel is dead, we only count it as dead.  If it is alive, but not addressable (maskable), we call it un-addresable (un-maskable).  What do we call a pixel which is alive but not addressable and not maskable?  I suspect this is exceeding rare, but Im curious.

Thanks.

Regards,
John

##########################
John Stupak III

Postdoctoral Research Associate
Purdue University Calumet
jstupak@fnal.gov<mailto:jstupak@fnal.gov>
508-254-5387
skype: JohnStupak
gChat: JohnStupak
##########################

On Apr 29, 2015, at 12:50 AM, Urs Langenegger <notifications@github.com<mailto:notifications@github.com>> wrote:

Is this a dead pixel?

If yes, would you then also count it as an address-decoding error? If
the answer is "yes", would you conclude similarly for the mask test
(which has much stricter implications)? Imho, a dead pixel is a dead
pixel and should not count towards address or mask defects (as it will
not deteriorate the performance in the sense of those defects).

We once had a three-state display for the address decoding (and mask
defect) histograms, showing -1, 0, and +1 to show the difference
between bad, dead, and good pixels. This was considered not good. So
now we are at a binary display.

The text output is not restricted by this limitation.

It's not clear to me this is a bug.

But it all rests on the question whether your blank pixel is dead or not.

Cheers,
--U.

**Comment by ursl** [comment]
Hi John,

> These pixels are indeed dead. I understand your logic that these unaddressable and dead pixels should only be counted as dead and not also be counted as unaddressable. But then I still argue there is an inconsistency between the log and the root output. If we are not counting these pixels as unaddressable, why don’t they show up as red on the plots? This is quite confusing..

Yes, there is an inconsistency. However, making the printout agree
with the histogram discards information (which is not necessary,
imvho).

They do not show up as red because we don't know they are OK. (One
could argue that "red" is misleading for "OK", but ...) As I said,
imvho this should be a three-state plot (bin contents -1, 0, +1), but
that was considered confusing as well. We can discuss this at the next
pxar meeting (and one would need to check what moreweb does) whether
we want to go (back) to a three-state plot.

pXar tests (so far) are (mostly) stateless, in the sense that a test
does not require knowledge from a previous test. (DAC settings are a
somewhat different topic, e.g. nothing would really work w/o a
pretest, the PH optimization test benefits from a trimmed detector,
etc.) But for the interpretation of a test, the pre-history is
important (e.g. this discussion). This is where moreWeb adds real
benefits. For pXar there are places where things should change: the
trimming is most likely not really good when you have a 'bad' ROC, and
likely high-rate tests will have biased performance numbers for bad
ROCs. (For production testing this is probably an academic issue:
Modules with bad ROCs are probably not used, so their performance
numbers are not essential.)

> From your explanation, I understand that if a pixel is dead, we only count it as dead. If it is alive, but not addressable (maskable), we call it un-addresable (un-maskable). What do we call a pixel which is alive but not addressable and not maskable? I suspect this is exceeding rare, but Im curious.

I assume that you mean "un-addressable" = "address-decoding error",
i.e. the address returned by the pixel is not correct. So the
situation you describe is (if I understand correctly) simply a pixel
that is alive, cannot be masked and returns the wrong address. Yes,
this is rare. In the previous production, the mask defect occurred
with < 4.e-7 probability. A pixel that cannot be masked was a reason
to reject a ROC (and module). I think we had 4-5 ROCs which had a
total of 23-24 mask-defect pixels (at +17 and -10 degrees). Pixels
with address decoding errors occurred a bit more often, but still very
low probability (~1e-6).

Cheers,
--U.

**Comment by jstupak** [comment]
Hello Urs,

Thanks for the explanation.

This was a minor issue for me.  I am parsing the logs and the root files from pXar to collect information which we (FPIX) want to store in a module testing database.  One of these pieces of info is the list of all address-decoding error pixels, which I am taking from the TH2s.  To get this right, I had to link the results from the alive test and address decoding test, and determine which pixels have 0 bin content in the address decoding plot and >0 bin content in the corresponding pixel alive plot.  Its not a big deal, but something to think about since it may effect moreweb as well.  I have no opinion since I already worked around this.

Regards,
John

##########################
John Stupak III

Postdoctoral Research Associate
Purdue University Calumet
jstupak@fnal.gov<mailto:jstupak@fnal.gov>
508-254-5387
skype: JohnStupak
gChat: JohnStupak
##########################

On Apr 29, 2015, at 10:17 AM, Urs Langenegger <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi John,

> These pixels are indeed dead. I understand your logic that these unaddressable and dead pixels should only be counted as dead and not also be counted as unaddressable. But then I still argue there is an inconsistency between the log and the root output. If we are not counting these pixels as unaddressable, why don’t they show up as red on the plots? This is quite confusing..

Yes, there is an inconsistency. However, making the printout agree
with the histogram discards information (which is not necessary,
imvho).

They do not show up as red because we don't know they are OK. (One
could argue that "red" is misleading for "OK", but ...) As I said,
imvho this should be a three-state plot (bin contents -1, 0, +1), but
that was considered confusing as well. We can discuss this at the next
pxar meeting (and one would need to check what moreweb does) whether
we want to go (back) to a three-state plot.

pXar tests (so far) are (mostly) stateless, in the sense that a test
does not require knowledge from a previous test. (DAC settings are a
somewhat different topic, e.g. nothing would really work w/o a
pretest, the PH optimization test benefits from a trimmed detector,
etc.) But for the interpretation of a test, the pre-history is
important (e.g. this discussion). This is where moreWeb adds real
benefits. For pXar there are places where things should change: the
trimming is most likely not really good when you have a 'bad' ROC, and
likely high-rate tests will have biased performance numbers for bad
ROCs. (For production testing this is probably an academic issue:
Modules with bad ROCs are probably not used, so their performance
numbers are not essential.)

> From your explanation, I understand that if a pixel is dead, we only count it as dead. If it is alive, but not addressable (maskable), we call it un-addresable (un-maskable). What do we call a pixel which is alive but not addressable and not maskable? I suspect this is exceeding rare, but Im curious.

I assume that you mean "un-addressable" = "address-decoding error",
i.e. the address returned by the pixel is not correct. So the
situation you describe is (if I understand correctly) simply a pixel
that is alive, cannot be masked and returns the wrong address. Yes,
this is rare. In the previous production, the mask defect occurred
with < 4.e-7 probability. A pixel that cannot be masked was a reason
to reject a ROC (and module). I think we had 4-5 ROCs which had a
total of 23-24 mask-defect pixels (at +17 and -10 degrees). Pixels
with address decoding errors occurred a bit more often, but still very
low probability (~1e-6).

Cheers,
--U.

**Comment by ursl** [comment]
Hi all, 

I changed the display to be now "tri-state" for the address decoding test and the mask test. -1 is shown as red and implies faulty pixel, 0 is shown white and implies a dead pixel, 1 is shown in green and implies working pixel (where working means correct address or maskable, respectively). 

For the mask test, a pixel alive test must be run beforehand. If this has happened, the mask test will use those results. If it has not happened beforehand, it will run it (but the pixelalive results will not appear). This is not necessary for the address decoding test, as there we get back something from a pixel if it is not dead, while for the mask test nothing is expected for a working pixel and for a dead pixel. 

This change should be transparent to moreweb (in fact likely fixes an issue that moreweb expected mask defects to be indicated by bin contents < 0, while in the past pXar reset those to 0 for the binary display logic). 

Please re-open if there are issues with this that I did not see today. 

Cheers,
--U.
