### ISSUE TITLE
readback calibrateia bug for modules

### ISSUE THREAD

**Issue by piberger** [psi46/pxar#336]
Hello,

i noted negative values for the testboard calibration fit in "calibrateia" test, which came from a wrong current offset substraction. Adding a delay between the setDAC() and the getTBia() helped to get the correct current offset.

PixTestReadback.cc: line 432
```
  //measuring average current offset from other ROCs
  //  vector<uint8_t> readback_offset;
  double ioff16=0.;
  fApi->setDAC("vana", 0);
  ioff16 = fApi->getTBia()*1E3;
  double avIoff=0;
  avIoff = ioff16*(readback.size()-1)/(readback.size());
```

**Comment by vtavolar** [comment]
Thanks Pirmin for spotting this, I am working on updating the readback test and I had already realized this problem. I think it is not worth to fix it in the master branch since a new/debugged version of the test should come soon from my side.

Vittorio

**Comment by piberger** [comment]
closed
