### ISSUE TITLE
helper.h::expandSign(uint16_t x)

### ISSUE THREAD

**Issue by ursl** [psi46/pxar#341]
Hi Simon,

why is  expandSign(uint16_t x)

 static int16_t expandSign(uint16_t x)

and not 

 int16_t inline expandSign(uint16_t x)

? This causes (clang) compiler warnings for all files that include helper.h but do not use expandSign.

Cheers,
--U.

**Comment by simonspa** [comment]
Hi Urs,

no particular reason, probably just bad coding. I fixed it and it's here together with some other fixes:
https://github.com/simonspa/pxar

Would be great if you could test that branch. Shall I create a PR?

/Simon

**Comment by ursl** [comment]
Hi Simon,

 I am not sure which branch you refer to. Why not commit directly into
psi46/pxar? I checked that the "inline" at least compiles (before I asked).

Cheers,
--U.

**Comment by simonspa** [comment]
Hi Urs,

sorry, forgot to mention this, I was referring to the master branch. I created a pull request just now.

/Simon

**Comment by simonspa** [comment]
Fixed by #342
