### ISSUE TITLE
Missing item in documentation

### ISSUE THREAD

**Issue by veloxid** [psi46/pxar#348]
Hi 
I realised that the FAQ page should be modified for the ftdi driver:
if one uses the ftdi2xx driver and one installs it as written in the readme file, the headers are missing. 
So maybe we should add that the header files have to copied into the directory /usr/local/include

Cheers
Felix

**Comment by ursl** [comment]
Thanks. I added a remark to the "Prerequisites" section. If you have a specific error message from your use case, please consider adding it to the "Computer/software problems" section. 

Cheers,
--U.
