### ISSUE TITLE
Export xNoiseMap S-curves to .dat file

### ISSUE THREAD

**Issue by piberger** [psi46/pxar#349]
Hi,

I think it would be useful to also have the s-curves of the x-ray noise test (xNoiseMap) exported as (X)SCurveData_C*.dat file for analysis with MoReWeb. Either with an additional X to distinguish from normal s-curves or just under the same name as they are probably in separate test folders anyway.
What do you think?

**Comment by ursl** [comment]
Should be fixed in 3d94b9f3ba3429a72c255ff7125b6938df6e7f1f
