### ISSUE TITLE
Problems Compiling under MacOs 10.10.3

### ISSUE THREAD

**Issue by jking79** [psi46/pxar#353]
I am running into this error trying to comply head version of par:

4 warnings generated.
Linking CXX shared library libpxarana.dylib
Undefined symbols for architecture x86_64:
  "TObject::SavePrimitive(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*)", referenced from:
      vtable for PixInitFunc in PixInitFunc.o
  "ROOT::Fit::FitResult::PrintCovMatrix(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const", referenced from:
      anaGainPedestal::test(double, double) in anaGainPedestal.o
      anaScurve::test(double, double) in anaScurve.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [ana/libpxarana.dylib] Error 1
make[1]: *** [ana/CMakeFiles/pxarana.dir/all] Error 2
make: *** [all] Error 2

Ae there any suggestions on circumventing this issue?

Thank You
Jack King

**Comment by ursl** [comment]
Hi Jack,

what ROOT version are you using?

Cheers,
--U.

​

**Comment by jking79** [comment]
Urs,
I installed Root6 yesterday prior to attempting the build.  I was running Root5.  

Thank You for the help with this,
Jack King  


     On Wednesday, June 17, 2015 12:29 AM, Urs Langenegger <notifications@github.com> wrote:
   

 Hi Jack,

what ROOT version are you using?

Cheers,
--U.

​

**Comment by ursl** [comment]
Hi Jack,

I am not really sure whether your problems now arose ONLY in ROOT6 or also
in ROOT5. If in ROOT6, then please note that at the moment there is no
support for ROOT6. If in ROOT5, then we'll try to solve this. But I'd need
the detailed ROOT version for that (e.g. 5.34/02 or whatever).

Cheers,
--U.

**Comment by jking79** [comment]
Urs,

Following up on insuring proper linkage root 6, pervious problem fixed.
Now i get:

In file included from input_line_11:10:
In file included from /Users/kucms/Desktop/Testing/pxar1.9/pxar/ana/PixInitFunc.hh:6:
In file included from /opt/local/libexec/root6/include/root/TString.h:41:
In file included from /opt/local/libexec/root6/include/root/RStringView.h:26:
/opt/local/libexec/root6/include/root/RWrap_libcpp_string_view.h:502:4: error: redefinition of '__str_find_last_not_of'
   __str_find_last_not_of(const _CharT *__p, _SizeT __sz,
   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:1158:1: note: 
      previous definition is here
__str_find_last_not_of(const _CharT *__p, _SizeT __sz,
^
Error: /opt/local/libexec/root6/bin/rootcint: compilation failure (/Users/kucms/Desktop/Testing/pxar1.9/pxar/build/ana/anaDict551977e0e0_dictUmbrella.h)
make[2]: *** [ana/anaDict.cxx] Error 1
make[1]: *** [ana/CMakeFiles/pxarana.dir/all] Error 2
make: *** [all] Error 2

Do You, or anyone please, have an idea on how to solve this problem?

Thank You

Jack

**Comment by jking79** [comment]
Thank You for the assistance Urs and Robert,

I have a so far, good installation now.

Jack

**Comment by ursl** [comment]
Hi Jack and Robert,

is there something to be changed in pxar for it to be ROOT6 compliant?

Cheers,
--U.
​

**Comment by simonspa** [comment]
Some time ago I successfully compiled pxar w/ ROOT6 after a few fixes:
6043398674da1d00554213f57cdf65d99b56f83a
69a4fa4dd46b373507a47b8ecef6a3062c925d82
Since then I'm solely using ROOT6 to compile, but it's a Linux machine so some modifications might be needed (maybe similar to the ones quoted above)

**Comment by ursl** [comment]
do you also compile the GUI? It relies heavily on the dictionary and I'd be
really impressed if there the transition from ROOT 5 to 6 had no negative
impact.

Cheers,
--U.

**Comment by jking79** [comment]
Urs,
After review I find that all the modifications Simon indicates are already included in current head.  I did not get the head to compile on MacOs 10.10.3 with ROOT6.   I had to reset back to ROOT 5.
Jack 


     On Wednesday, June 17, 2015 5:11 PM, Urs Langenegger <notifications@github.com> wrote:
   

 do you also compile the GUI? It relies heavily on the dictionary and I'd be
really impressed if there the transition from ROOT 5 to 6 had no negative
impact.

Cheers,
--U.

**Comment by simonspa** [comment]
Hi @ursl,

yes, this was with the full GUI and tests set, since pxarCore has no root dependency at all.
I was surprised myself how well it went with the only changes necessary are the C++11 compliant compiler and this single changed incompatible return value...

/simon

**Comment by ursl** [comment]
Hi all, 

fwiw: I compiled pxar with ROOT 6.04/02 (compiled from source) on Ubuntu 14.04.2 LTS and everything (including GUI and tests) seems to run fine. I see error messages 

Error in <TCling::RegisterModule>: cannot find dictionary module anaDict_rdict.pcm
Error in <TCling::RegisterModule>: cannot find dictionary module utilDict_rdict.pcm
Error in <TCling::RegisterModule>: cannot find dictionary module testsDict_rdict.pcm
Error in <TCling::RegisterModule>: cannot find dictionary module usertestsDict_rdict.pcm
Error in <TCling::RegisterModule>: cannot find dictionary module guiDict_rdict.pcm

but they do not seem to affect the program execution. I'll fix these eventually (the *.pcm files need to be in the same directory as the .so files, I think). 

In fact, I think it is pretty amazing, that changing from CINT to CLING "everything" "just" continues to work. New ROOT versions have caused much more trouble in the past with much less changes ...

Cheers,
--U.
