### ISSUE TITLE
TBM08c testing

### ISSUE THREAD

**Issue by minano** [psi46/pxar#360]
mkConfig does not have the default parameters for TBM08c.
What the recommendation procedure?

**Comment by thweiler** [comment]
Hello Mercedes
We use the Parameters of TBM08B at the moment, they work on our repsin modules with TBM08C.
May be @ursl can add them to the mkConfig.

Cheers
Thomas

**Comment by ursl** [comment]
Hi all, 

c3566a7cd917dde28bd43d0705d3b91095ef04b4 has a TBM08C (and defaults to it). 

Cheers,
--U.
