### ISSUE TITLE
request to add the deserializer/channel nr to the data stream

### ISSUE THREAD

**Issue by werdmann** [psi46/pxar#363]
Asking mostly Urs and Simon,
  modules with one or two tbm09c use multiple data channels and it seems to be helpful to be able to trace back data to the channel.
This information is dropped by the daq functions. I would propose to store it in the unused bits of the tbm header words.  This could be  implemented by  replacing
  void dtbEventSplitter::SplitDeser400() {
    ...
    // If new sample does not have start marker keep on reading until we find it:
    if ((GetLast() & 0xe000) != 0xa000) {
      record.SetStartError();
      Get();
    }
    record.Add(GetLast());

with
    
  void dtbEventSplitter::SplitDeser400() {
    // If last one had Event end marker, get a new sample:
    if (!nextStartDetected) { Get(); }

    // If new sample does not have start marker keep on reading until we find it:
    if ((GetLast() & 0xe000) != 0xa000) {
      record.SetStartError();

**Comment by werdmann** [comment]
Sorry, accidentally hit the submit button too early.
So the proposal is to replace 
record.Add(GetLast());
 with
record.Add(GetLast() | ( (GetChannel() & 0x7)<<8 ) );

I have not seen any side effects. If you have any objections, please let me know.

**Comment by simonspa** [comment]
Hi Wolfram,

perfectly fine with me, using unused bits sounds like a good idea anyway.
Maybe adding a comment to the line?

```
// Store the TBM header word and attach the channel ID:
record.Add(GetLast() | ( (GetChannel() & 0x7)<<8 ) );
```

Currently in the global `pxar::Event` we are only storing the TBM header of the first channel which is clearly sub-optimal. I would suggest changing this to a vector or so to store all TBM headers and trailers. However, I want to look into the memory consumption implications of this before...

**Comment by simonspa** [comment]
If we extend `pxar::RawEvent` with
```
    uint8_t GetChannel() { return ((data.front() >> 8) & 0x7); }
```
we can easily retrieve the information from the event again.
