### ISSUE TITLE
Incorrect token chain length with bypassed ROCs

### ISSUE THREAD

**Issue by drberry85** [psi46/pxar#368]
Hey Simon,

There is a bug in pXar were the token chain lengths are either not calculated correctly or not updated when custom ROC configurations are used. When I set ```nRocs 15 i2c: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15``` I can see the configuration is correct:
```
[17:04:49.298]     INFO: custom i2c addresses:  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
```
But I can see the token chain lengths are not correctly calculated.
```
[17:04:49.538] DEBUGAPI: <api.cc/initDUT:L292> TBM Core Alpha Token Chains: 8 
[17:04:49.538] DEBUGAPI: <api.cc/initDUT:L292> TBM Core Beta Token Chains: 8 
```
which causes an error
```
[17:04:49.540] CRITICAL: <api.cc/initDUT:L351> Hm, we have 15 ROC configurations but a total token chain length of 16 ROCs.
[17:04:49.540] CRITICAL: <api.cc/initDUT:L352> This cannot end well...
pxar caught an exception due to invalid configuration settings: Mismatch between number of ROC configurations and total token chain length.
```
Doug

**Comment by simonspa** [comment]
Hi Doug,

since we can't know on which TBM channel the ROC is missing, you have to tell us so by setting the "nrocs 7" parameter for the TBM core where the ROC is missing (e.g. in `tbmParameters_C0a.dat`)

Cheers,
Simon

**Comment by drberry85** [comment]
Simon,

You're right, my mistake. I forgot about the token length variable in the tbm configuration dats.

Thanks for the help,
Doug

**Comment by simonspa** [comment]
Actually, your are right - we could do this smarter and automatically assign the ROC to the correct token chain. As long as the module is build according to the standards the I2C address defines the port of the ROC and thus also the token chain.

Could you maybe remove the two "nrocs" settings again and check with my master branch? https://github.com/simonspa/pxar/commits/master

thanks.
