### ISSUE TITLE
Filter dead pixel out in phOptimization test

### ISSUE THREAD

**Issue by pohsun** [psi46/pxar#369]
I just realized that dead pixel could be used in phOptimization and gives 0 for both scale and offset.
There must be some tools to detect dead pixels, 
could you please integrate this auto-detect step into the test?

**Comment by piberger** [comment]
Hi,
Isn't BlacklistPixels doing this?
https://github.com/psi46/pxar/blob/master/tests/PixTestPhOptimization.cc#L209
or did I understand your post wrong?

**Comment by pohsun** [comment]
Hi,
I don't think so. I ran the phOptimization to two modules which have a big region of defects, and obviously the results is totally bad for the rocks with defects. Is there any way to specify the pixel for this testing? I can test if BlacklistPixels works fine by taking the test with good pixels.

**Comment by ursl** [comment]
Hi, 

it should be possible to use defaultMaskFile.dat to declare dead pixels. As far as I understand the code in PixTestPhOptimization, this should be used there as well. If not, please post. 

On a different note: Just from a superficial code browsing it is not obvious that the result of BlackListPixels is used in optimiseOnMapsNew. IF this is indeed missing, then it should be fixed. 

Cheers,
--U.

**Comment by ursl** [comment]
Another followup: Maybe also the defaultMaskFile.dat mechanism is not enough to cure the optimization. But I am not sure about this.
