### ISSUE TITLE
VIColor default setting

### ISSUE THREAD

**Issue by jhoss** [psi46/pxar#373]
In the mkConfig script the default VIColOr setting is still 10 for digV2.1respin and digV2.1 ROCs. This is a remnant introduced for the digV2 ROC to minimize double column freezing and should now be set back to the default of 100 for digV2.1respin and digV2.1 ROCs. Proposal in agreement with Hans-Christian.

Cheers

      Jan

**Comment by simonspa** [comment]
Is there a reason not to increase it to 220 or so? This is the setting we found to be more efficient in the Testbeam. With lower settings long clusters are more likely to lose single pixels in a double column. This is especially important for chips mounted towards higher eta where long clusters over many columns are expected.

**Comment by jhoss** [comment]
There is no drawback that I know of and in Visegrad you stated that Hans-Christian also agreed with this. But VIColOr=10 is definitely too low.

**Comment by simonspa** [comment]
Yes, I agree, 10 should definitely not be a default.

Am 14. Juli 2015 17:16:13 MESZ, schrieb jhoss <notifications@github.com>:

**Comment by ursl** [comment]
I talked to Hans-Christian and he recommended 100. I changed to that in 0fc1ad755c6f8e8662a0d84a9771620723e274d4.
