### ISSUE TITLE
clarification about pixel Alive test

### ISSUE THREAD

**Issue by MDallOsso** [psi46/pxar#375]
Hi all, 
        this is just a question for clarification.
I am not contributing to the code since a while and I would like to know if there have been changes in the basic tests: Alive/BB.

- Alive -> which defect are taken into account in the Pixel Alive map? Dead pixels only or even defect mask bit, ...? I mean, if a pixel is white in the map it means that it is dead or there can be other defects?
- BB -> the 'white' pixels from Pixel Alive are tested in the Bump Bonding procedure or they are skipped?

Thank you,
Martino

**Comment by ursl** [comment]
Hi Martino, 

in the alive map, only dead (problematic) pixels are reported. It is simply a histogram of hits vs col/row. If there are pixels with address decoding errors (i.e. pixels responding with a wrong address ["other" pixel]) this will appear as pixels with >100% efficiency (assuming that the "other" pixel is fully efficient) and <100% efficiency for the "true" pixel location. I hope you understand what I mean with this.

The situation can be disentangled by also looking at the AddressDecodingTest and the MaskTest map, where such cases are caught explicitly. (A mask defect should not lead to problems/artefacts in the alive test except in cases where there is excessive cross talk.)

The BB test runs over all pixels (modulo those specified to be masked in defaultMaskFile.dat). We (mostly) do not keep state information in pxar between tests. So dead pixels will appear as unbonded. 

I hope this answers your question.

Cheers,
--U.

**Comment by MDallOsso** [comment]
Dear Urs,
      thank you for the answer.
Yes, I think that now it is more clear. It is fine to have no communication between BB and Alive tests.
I posed this question because we get in our bare modules test a number of 'dead' pixels (small) always greater than the BB fails. We will cross-check and let you know.

Cheers,
Martino
