### ISSUE TITLE
Ethernet Connectivity

### ISSUE THREAD

**Issue by cfangmeier** [psi46/pxar#38]
Last fall I wrote some code in psi46test and in the NIOS part of the firmware to enable communication between the host machine and a DTB via Ethernet. This involved creating another RPC implementation similar to what exists for USB. I would like to add this functionality to pxar. 

Core developers: When would be a good time for me to begin work on this?

**Comment by simonspa** [comment]
All code concerning Ethernet support has been merged some time ago. As soon as we have a firmware supporting this we can start debugging it.

Closing this ticket since pxarCore has Ethernet support (build with -DINTERFACE_ETH=ON)
