### ISSUE TITLE
SCurveData: wrong numbr of triggers in file

### ISSUE THREAD

**Issue by thweiler** [psi46/pxar#382]
Hi
In  the SCurveData_C*.dat should state 'Mode1 Ntrig 50' (or the selected total number of triggers) instead of 'Mode1 Ntrig 2'.

Furthermore, there are a lot of SCurves starting at too low thresholds and therefore are not fitted in MoReWeb (see vcalthreshold map below)

![vcalthreshold](https://cloud.githubusercontent.com/assets/7323782/8953824/987ca272-35e1-11e5-84b9-a86dcf1f61f3.png)

example from SCurveData_C0.dat
32  90   0   0   0   0   0   1   1   3   3   7  10  15  13  20  26  29  31  37  41  44  45  50  50  50  50  50  50  50  50  50  50  50
32  85   0   0   0   0   0   0   0   0   1   8   3   9  16  20  22  27  39  36  40  39  42  47  49  49  49  50  50  50  50  50  50  50
32  91   0   0   0   1   0   1   1   4   7   9  13  10  20  15  25  30  39  44  42  46  49  50  50  50  50  50  50  50  50  50  50  50
32  97   0   0   0   0   1   0   0   0   0   1   8   9   9  22  28  32  41  46  45  48  49  50  50  50  50  50  50  50  50  50  50  50
32  98   0   0   0   0   0   0   0   1   1   3   9   7   7  29  37  36  42  47  48  49  50  50  47  49  50  50  50  50  50  50  50  50
32  99   0   0   0   0   0   0   0   0   1   3   2   4  20  25  31  34  39  47  48  45  49  49  47  50  49  50  50  50  50  50  50  50
32 106  18  26  36  40  44  47  49  49  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50
32 101   6   2   2   5  13  13  23  24  28  35  48  46  49  49  49  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50
32  98   0   2   5   4   5   4   3  13  15  25  31  30  40  49  50  50  48  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50
32  92   0   0   0   0   1   0   1   5   4   6   9   8  18  22  27  34  37  44  43  47  49  50  50  50  50  50  50  50  50  50  50  50
32  92   0   0   0   0   0   1   1   1   4   5   9   9  19  25  19  28  37  41  44  50  47  49  50  50  50  50  50  50  50  50  50  50
32  97   1   0   3   3  12   9  16  18  19  25  30  39  44  45  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50
32 110  45  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50  50

cheers
Thomas

**Comment by ursl** [comment]
Hi Thomas, 

many thanks for this report. This bug got in when I added the ntrig/step workaroung to the r/o problems. 

I have fixed this in the master branch and the production branch, in particular tag prod-03. The latter would be my recommendation if people want a stable production module testing release. 

Cheers,
--U.
