### ISSUE TITLE
Event ID Mismatch Bug in Deserializer

### ISSUE THREAD

**Issue by drberry85** [psi46/pxar#386]
Simon and Urs,

The local event ID in the deserializer needs to be reset to 0 after asking for daq triggers. Currently it's not reset, which causes and error after calling multiple triggers in a row:
```
  fApi->daqStart();
  fApi->daqTrigger(32, period);
  daqEv = fApi->daqGetEventBuffer();
  fApi->daqTrigger(32, period);
  daqEv = fApi->daqGetEventBuffer();
  fApi->daqStop();
```
This causes a read back error because ```fApi->daqTrigger(32, period);``` resets the TBM ID but not the local event ID, which stuck at 32:
```
[12:07:38.415]    ERROR: <datapipe.cc/CheckEventID:L446> Channel 0 Event ID mismatch:  local ID (32) !=  TBM ID (0)
[12:07:38.415]    ERROR: <datapipe.cc/CheckEventID:L446> Channel 1 Event ID mismatch:  local ID (32) !=  TBM ID (0)
```
Let me know if this is a feature and not a bug. If it's a feature, then we need an API call that will allow us to reset this value.
Doug

**Comment by simonspa** [comment]
Hi @drberry85,

I consider this clearly a bug, introducing another call for something that can be done automatically doesn't seem practical to me.

However, I can't see where this happens - neither in `daqTrigger()` nor in `daqGetEventBuffer()` anything is touched or reset in the TBM. Only if your Patter Generatur setup contains a TBM reset something like this could happen.

I would need your exact PG setup and an output of the error occurring with DEBUGPIPES level if possible. I will then implement the automatic reset of the internal event ID on a TBM reset.

Cheers,
Simon

**Comment by simonspa** [comment]
I commited a possible fix in my master branch, which detects the TBM Reset bit in the trailer and treats the local event ID accordingly.

I'm however still interested in your debug output to cross-check before merging.

**Comment by drberry85** [comment]
Simon,

This was my mistake, and it should have never been reported. The problem is in the DTB emulator and nothing is wrong with the decoding. I forgot to check the problem with a real module before I created the issue. I just double checked this in both your branches head and psi46 head and everything works great with a real module.

Sorry,
Doug

**Comment by simonspa** [comment]
Hi @drberry85, funny that you report this, because I fell for exactly the same thing when trying to reproduce your error. Do you have any way to still check if the TBM Reset fix works?

E.g. running a real module once with and once without TBM Reset in the PG and compare the result. Would be a nice-to-have feature I guess.

And sorry for the imperfect emulator... ;)

**Comment by drberry85** [comment]
Simon,

Yes, when I insert a TBM reset in to pg_setup the event number is always 1 and does not cause an error.

Doug

**Comment by simonspa** [comment]
Okay. Do you get errors without the patch?

**Comment by drberry85** [comment]
Simon,

Yes, when I use the main branch of pXar I do get an error when I include a TBM reset in the pg_setup.
```
[15:33:24.613]    ERROR: <datapipe.cc/CheckEventID:L446> Channel 0 Event ID mismatch:  local ID (2) !=  TBM ID (1)
[15:33:24.614]    ERROR: <datapipe.cc/CheckEventID:L446> Channel 1 Event ID mismatch:  local ID (2) !=  TBM ID (1)
[15:33:24.614]    ERROR: <datapipe.cc/CheckEventID:L446> Channel 0 Event ID mismatch:  local ID (2) !=  TBM ID (1)
[15:33:24.614]    ERROR: <datapipe.cc/CheckEventID:L446> Channel 1 Event ID mismatch:  local ID (2) !=  TBM ID (1)
```
Doug

**Comment by simonspa** [comment]
Thanks Doug for testing, so the fix goes in. Great!
