### ISSUE TITLE
Issue of IV scan

### ISSUE THREAD

**Issue by jstupak** [psi46/pxar#390]
Hi,

I am having issue with the IV scan test. 
When I running the test. This info showed in the terminal:
 "[17:24:40.005] CRITICAL: <rs232.cc/readData:L323> [RS232] Serial Timeout". 
Then pxar stopped doing the IV scan and gave me this warning:
"[17:24:44.813]  WARNING: Sweep Aborted on Compliance!"
The compliance I set was at 100 uA, but I got this warning when the current only at 9uA or 10 uA.
I have verified that the settings on the Keithley match those recommended by pXar.
What should I do to fix this problem?
Thanks!

Xuan

**Comment by ursl** [comment]
Hi Xuan, 

I think you have no compliance problem, but likely a connection problem? Without a full log file this is a bit difficult. We could change the error message, but that will not solve your problem.

Cheers,
--U.
