### ISSUE TITLE
Statistics printing after FullTest

### ISSUE THREAD

**Issue by simonspa** [psi46/pxar#393]
Hi Urs,

it would be really an advantage to accumulate the decoding statistics for all tests and print them after the full test has finished. Coding wise it's pretty darn simple since statistics objects have their `+=` operator overloaded so we can just add them together:

```
pxar::statistics my_global_stats;

while (tests) {
  _api->doMyTest()
  pxar::statistics my_test_stats = _api->getStatistics();
  // Do something with the current statistics, like checking errors:
  size_t errors = my_test_stats.errors();

  // Add them to the global run statistics:
  my_global_stats += my_test_stats;
}

// Print the total summary:
my_global_stats.dump();
```

The reason for this is that we see huge error numbers (partly negative) in the test printout, but this seems to come from non-initialized variables - the statistics object returns only `uint32_t` counters which cannot be negative.
Browsing through the actual tests I don't see a single decoding error printed. Just to make sure I need the full statistics printout since some (pixel decodings) are not printed on screen during decoding.

In general it seems like a nice feature to have.

Cheers,
Simon

**Comment by ursl** [comment]
https://github.com/psi46/pxar/commit/f16e873fbfe330786d93b1df2765acfb466cc9de does at least the summary (and per test) stats dump.
