### ISSUE TITLE
Correctly initialize fNDaqErrors

### ISSUE THREAD

**Issue by simonspa** [psi46/pxar#394]
Hi Urs,

apparently the variable `uint32_t fNDaqErrors` in https://github.com/psi46/pxar/blob/master/tests/PixTest.hh#L323 is not correctly initialized to zero anywhere. I see this, since one test (BB2) reads from the variable without using any PixTest class function beforehand, but calling the API object directly.
When doing this we get memory garbage back. Probably we should add it to the initialization list in https://github.com/psi46/pxar/blob/master/tests/PixTest.cc#L29:

```
PixTest::PixTest(PixSetup *a, string name) : fNDaqErrors(0) {
   ...
}
```

Cheers,
Simon

**Comment by ursl** [comment]
Hi Simon,

I have nothing against initializing it.

BUT: Your (or whoever's) problem is that you use a variable n the wrong
context (I think). fNDaqErrors is used in helper functions in PixTest, and
if you use those it is always well set. BB2 however chose not to use the
helper functions and makes api calls directly. This is fine, but then BB2
should not blindly dump a variable that is of no use to it and which it has
not set.

So I would propose that you (or whoever) also corrects the printout in BB2.

Cheers,
--U.

**Comment by ursl** [comment]
fixed.

**Comment by simonspa** [comment]
I indeed agree on this. I'd you would make the variable private in PixTest no child class could access it.

Am 26. August 2015 07:20:33 MESZ, schrieb Urs Langenegger <notifications@github.com>:

**Comment by ursl** [comment]
Hi Simon,

but as it is implemented at the moment it is used in derived classes
(arguably a feature).

Things could be solved differently, for sure. And I do not like
uninitialized variables, and therefore it is fixed now in the master
branch.

Cheers,
--U.
