### ISSUE TITLE
USBInterface core dumped ...

### ISSUE THREAD

**Issue by dinardo** [psi46/pxar#398]
While running on a chip 2.0 version I get the following CRITICAL error:

[14:20:52.974] CRITICAL: <USBInterface.libftdi.cc/Read:L480>  Timeout reading from USB buffer after 150000 ms 
[14:20:52.974] CRITICAL: <USBInterface.libftdi.cc/Read:L482> Requested to read 1b, actually read  0b - 1b missing!
terminate called after throwing an instance of 'CRpcError'
Aborted (core dumped)

The system configuration is:
--- DTB info------------------------------------------
Board id:    120
HW version:  DTB1.2
FW version:  4.2
SW version:  4.4
USB id:      DTB_WWV4F3
MAC address: 40D855118078
Hostname:    pixelDTB120
Operating system: SLC 6.7

My sequence of tests is:
Setup
PreTest
PixelAlive
BB
Scurves
Trim vcal=45
Scurves
PhOptimization saturationvcal=100
GainPedestal
q

The error occurs during the second "Scurves".
I sent the entire content of the configuration directory to Urs.

**Comment by piberger** [comment]
Hi,
we also had the same problem, in our case this was related to 2 specific testboards. These 2 testboards sometimes failed after few minutes, but most of the time after >1 hr. We didn't investigate it any further and replaced the 2 DTBs in the setup.
With Martins comments in the meeting it seems worthwhile to test these 2 DTBs again with open case and/or cooling. We will do this at some point and I can report the result here.

**Comment by dinardo** [comment]
Ok, I see.
I only would like to add that the problems occures when I initialize the test directory as psi v2, instead of I initialize the directory as psi v21 or psi v21respin the problem doesn't show up at all.

Do you suggest me to change the DTB with  another one?

Regards,
- Mauro.

**Comment by simonspa** [comment]
Hi Mauro,
is this reproducable, even with newly created config directories?
Could you upload the configurations somewhere where we can access them?

/Simon

**Comment by dinardo** [comment]
Hi Simon,
every time I run my sequence of tests I make a brand new directory.
All files in tar ball are available on my CERN public area:
/afs/cern.ch/user/d/dinardo/public/

The other strange thing is that the system was crashing when I had no bias voltage attached to the sensors. Instead when I started to bias the sensors, the crash never occurred ever again.
- You'll find the file ROCtest_noHV.tar.gz that contains the files when the system crashed (no HV applied). 
- You'll find the file ROCtest_yesHV.tar.gz that contains the files when the system didn't crash (HV applied).

Both were run with configuration made for a PSI digital chip 2.0
- Mauro.

**Comment by ursl** [comment]
Hi Mauro,

I (finally) looked at your logfile. You run the timing test, even though
your config file has nTBMs = 0 (and this is reflected in your pxar.log).
This should not be. The timing test in the pretest should only be run for
modules with TBM08C or TBM09C, and this is based on a call
to fApi->_dut->getTbmType(). By default that returns "" for no TBM. So I am
confused.

Then your USB problems start much earlier already. Your entire logfile has
them. In particular your trim test went nowhere because of them. Your first
scurve somehow managed to survive them.

How old is your computer?

Cheers,
--U.

**Comment by dinardo** [comment]
Hi Urs,
thanks for looking into this.
(a) how can I disable the timing test ?
(b) my computer is very new (one year), maybe the problems
is related to the fact that I'm running pXar from within an Oracle
Virtual-Box on a Windows computer ?
In the Oracle Virtual-Box I'm running SLC 6.7.
- Mauro.

**Comment by ursl** [comment]
Hi Mauro,

I work with the (HEAD of the) master branch, and if I run the pretest
on a single-ROC I get

[16:16:04.058]     INFO: PixTestPretest::setVana() done, Module Ia
23.3 mA = 23.3 mA/ROC
[16:16:04.060]  WARNING: pretest::findTiming only works for
TBM08c/09c! Do something on your own.
[16:16:04.061]     INFO:
----------------------------------------------------------------------
[16:16:04.062]     INFO:    PixTestPretest::findWorkingPixel()
[16:16:04.062]     INFO:
----------------------------------------------------------------------



This is very different from your setup:

[14:29:39.637]     INFO: PixTestPretest::setVana() done, Module Ia
24.1 mA = 24.1 mA/ROC
[14:29:40.194]     INFO:
----------------------------------------------------------------------
[14:29:40.194]     INFO:    PixTestPretest::findTiming()
[14:29:40.194]     INFO:
----------------------------------------------------------------------
[14:29:40.194]     INFO: PixTestCmd::init()
[14:29:40.194]    DEBUG: <PixTestCmd.cc/runCommand:L3654> running
command: timing
[14:29:40.334]  WARNING: Not unmasking DUT, not setting Calibrate bits!
[14:29:45.140]    DEBUG: <PixTestCmd.cc/~PixTestCmd:L77> PixTestCmd dtor
[14:29:45.140]     INFO: TBM phases:  160MHz: -1, 400MHz: -1, TBM
delays: ROC(0/1):-1, header/trailer: -1, token: -1
[14:29:45.140]     INFO: (success/tries = -1/-1)
[14:29:45.140]  WARNING: TBM registers not set !?! This is not going to work.
[14:29:45.140]  WARNING: error setting delay  base A ?
[14:29:45.140]  WARNING: TBM registers not set !?! This is not going to work.
[14:29:45.140]  WARNING: TBM registers not set !?! This is not going to work.
[14:29:45.162]     INFO:
----------------------------------------------------------------------
[14:29:45.162]     INFO:    PixTestPretest::findWorkingPixel()
[14:29:45.162]     INFO:
----------------------------------------------------------------------


In case you have not updated to the HEAD, please do so. The
alternative is to comment out the call to findTiming in
tests/PixTestPretest.cc::doTest().

I have run (successfully) with a VB (with UBUNTU) on osx, but it's
been a while. I've never done that on a windows machine.

Cheers,
--U.

**Comment by dinardo** [comment]
Hi Urs,
I'm pretty sure that I downloaded the HEAD few days ago
when we walked about using the new firmware 4.4.
Probably in these days you guys changed something else
in the head and from that point on I was behind.
Today I've re-downloaded the HEAD and indeed I get now
the same screen message as you do.
Many thanks for looking into this.
- Mauro.

**Comment by ursl** [comment]
Hi Mauro,

yes, the HEAD keeps on moving.

Cheers,
--U.

**Comment by dinardo** [comment]
Dear All,
after updating to HEAD I'm still having an "Abort" issue during
"Xray - phrun" test with "runseconds" = 1800.

The error message is:

CRITICAL: <USBInterface.libftdi.cc/reader:L70> ERROR during USB read polling: error code from libusb_bulk_transfer(): -7
terminate called after throwing an instance of 'pxar::UsbConnectionError'
  what():  ERROR during USB read polling
Aborted (core dumped)

All files are in my public CERN afs area: /afs/cern.ch/user/d/dinardo/public/
Many thanks,
- Mauro.

**Comment by ursl** [comment]
Hi Mauro,

I would say that you have a USB issue which has nothing per se to do
with pxar. Have you tried with a genuine *nix System?

Cheers,
--U.

**Comment by dinardo** [comment]
Hi Urs,
no, I haven't tried with a genuine *nix System.
- Mauro.

**Comment by simonspa** [comment]
...or just compile it natively under Windows? We have support fort that...

**Comment by dinardo** [comment]
Hi,
what does it mean:

[15:44:36.107] INFO: run duration 404 seconds, buffer almost full (81%), pausing triggers.
[15:48:57.899] INFO: Resuming triggers.

- The trigger rate is too high ?
- There are too many pixel cells responding ?
- Why does it take quite a while between "pausing triggers" and "resuming triggers" ?

Many thanks,
- Mauro.

**Comment by ursl** [comment]
the buffer on the DTB is running full and the computer is reading it out
via USB. That takes time.

Cheers,
--U.
