### ISSUE TITLE
Typo in pretest histogram title

### ISSUE THREAD

**Issue by lantone** [psi46/pxar#403]
Hi Urs,
    When collecting reference histograms for the testing documentation, I noticed a typo in this line (Vana -> Iana):
        https://github.com/psi46/pxar/blame/master/tests/PixTestPretest.cc#L354
   
Cheers,
Jamie

**Comment by ursl** [comment]
Hi Jamie, 

thanks. I think I fixed it (also the units). 

Cheers,
--U.
