### ISSUE TITLE
Unable to change parameters for "highrate:trimhotpixels"

### ISSUE THREAD

**Issue by ywkao** [psi46/pxar#413]
Hi,

When performing the retrim test with the command below,

*~/pxar/bin/pXar -d ~/pxar/data/ModuleName -T 35 -t highrate:trimhotpixels -p "trimhotpixelthr=10;runsecondsHotPixels=5;savetrimbits=1;maskuntrimmable=1" -v DEBUG*

I found that both "trimhotpixelthr" and "runsecondsHotPixels" are still the values recorded in the file "testParameters.dat".

I have try ohter tests like "Xray:phrun" or "HighRate:xnoisemaps", it works fine to change the  parameters by specifying the values in command line. Is there any possible reason why I am unable to assign the parameters' values  for the retrim test?

Thanks, 
Yu-Wei

**Comment by ursl** [comment]
Hi Yu-Wei,

the difference between the working example and the problematic one is
the capitalization. So try

~/pxar/bin/pXar -d ~/pxar/data/ModuleName -T 35 -t
Highrate:trimhotpixels -p
"trimhotpixelthr=10;runsecondsHotPixels=5;savetrimbits=1;maskuntrimmable=1"
-v DEBUG

and it should work.

Cheers,
--U.

**Comment by ywkao** [comment]
Hi Urs,

Yes, it is indeed the problem of capitalization! Finally, I try

*~/pxar/bin/pXar -d ~/pxar/data/ModuleName -T 35 -t
HighRate:trimhotpixels -p
"trimhotpixelthr=10;runsecondshotpixels=5;savetrimbits=1;maskuntrimmable=1"
-v DEBUG*

It can work fine.

Many Thanks!
Yu-Wei
