### ISSUE TITLE
random trigger support

### ISSUE THREAD

**Issue by werdmann** [psi46/pxar#418]
It seems that the random trigger generator of the DTB is currently not supported in pxar.
A possible implementation could be a new function like 

```
void hal::daqRandomTriggerSource(float fHz){

  uint32_t rate = int( fHz/40e6*4294967296 + 0.5);
  LOG(logDEBUGHAL) << "Configuring random trigger " << rate;

  // Write new trigger source to DTB:
  _testboard->Trigger_Select( TRG_SEL_GEN_DIR);
  _testboard->Trigger_SetGenRandom( rate );
  _testboard->Flush();
}
```

or a corresponding modification of the existing void hal::daqTriggerSource(uint16_t source)
together with a matching api function.

The current api function pxarCore::daqTriggerSource(std::string triggerSource)
can only be called when the daq is stopped.  I think this check should be removed or at least be configurable. In connection with a continously running trigger source like the random triggers it
seems necessary to stop the triggers before the daq is stopped and then let the daq run until
the data from all channels is collected. 

Wolfram

**Comment by simonspa** [comment]
Hi @werdmann 

I have a full implementation working but not merged to the main repo as it needs a bit more testing. The code is here:
https://github.com/simonspa/pxar
and will be merged probably tomorrow.

Two new sources "random" and "periodic" are available (also in the "_dir" version without TBM emulator) and a second parameter of `daqTriggerSource()` allows to select the trigger period/rate.

The second item mentioned is solved by only activating the trigger upon `daqStart()` and deactivating it at `daqStop()` (before the DAQ itself is stopped). This should allow consistent data acquisition without additional hassle. If this is not what you intended, please let me know.

Cheers,
Simon

**Comment by werdmann** [comment]
Hi Simon,

  I think this should basically do what is needed, thanks. The time between shutting off the trigger and stopping the daq does not seem to be controlled. In principle this could lead to incomplete events. I don't know whether in practice the time is always long enough to drain all channels with multiple stacked triggers.  What's the reason for prohibiting user access to the trigger settings while the daq is running ?
My understanding of the rate argument was that it is not in cHz or any other human readable frequency, so I don't understand your corresponding comment and logmessage.

Wolfram

**Comment by werdmann** [comment]
Hi Simon,  
I tested the code from your repository with "random_dir" and it works fine. 
Wolfram

**Comment by simonspa** [comment]
This should be fixed now. Trigger source changes are now allowed any time.
When measuring the trigger rate it appeared to be roughly equivalent to cHz, thus the comment and conversion. Not on the spot but in the same ball park.
