### ISSUE TITLE
D1 and D2 fields too short for signal names

### ISSUE THREAD

**Issue by werdmann** [psi46/pxar#420]
Some of the digital signals that can be selected in the D1 and D2 dropdown menus are much longer than the fields. This makes it hard to get the correct entry.
The longest one I see in  utils/dictionaries.h  is "deser_header_error" (18 characters)
According to my understanding there should be additional deser number attached to some so we would need at least 19 characters.

**Comment by ursl** [comment]
Hi Wolfram,

does
https://github.com/psi46/pxar/commit/7e0315c6cc0e4fe9e9e83d15923f0d01334510b8
fix this?

Cheers,
--U.

**Comment by werdmann** [comment]
Hi Urs,

 better, though still a bit too short for the longest names. Might be ok if the deser number is
attached at the beginning rather than the end.

Thanks,

Wolfram

**Comment by simonspa** [comment]
Hi @ursl and @werdmann 

there is (will be) a slight change in the API. The SignalProbe() function takes a second argument wich is the TBM channel:
```
bool SignalProbe(std::string probe, std::string name, uint8_t channel = 0);
```
which allows to select DAQ channel 0-8 for the `deser_` probes.

**Comment by ursl** [comment]
Hi Simon, 

0 .. 7 or 1 .. 8? At least with the dtbemulator I get a crash if I use 8, so I presume it is 0 ..7. Correct?

Many thanks. 

Cheers,
--U.

**Comment by simonspa** [comment]
Hi @ursl 

yes, sorry, it's 0-7. And I will also catch the crash in the pxarCore code...

/Simon

**Comment by simonspa** [comment]
hi again, this shoudl actially be caught already:

```
 // Check selected channel to be within range of valid DAQ channels:
  if(channel >= DTB_DAQ_CHANNELS) throw InvalidConfig("No DAQ available for selected channel.");
```
in https://github.com/psi46/pxar/blob/master/core/api/api.cc#L586

**Comment by ursl** [comment]
Please open again if not working.
