### ISSUE TITLE
Iana check in Pretest

### ISSUE THREAD

**Issue by piberger** [psi46/pxar#423]
Hi,

Pretest now stops (without writing good config parameters) if Iana drop is too little. Can we continue anyway (but still show the error message)?
We also want to qualify modules which have a too little Iana drop in the pretest as we have had a case where only a single ROC was affected.

**Comment by piberger** [comment]
update: I see Urs just posted a Hypernews about this at the same time

**Comment by ursl** [comment]
Hi Pirmin, 

please also comment in hn. [Sorry, I had to pay attention to a meeting so this was delayed.]

BTW, you can continue if you want by invoking the subtests of the pretest manually, e.g. 

Pretest:programroc
Pretest:setvana
Pretest:findtiming
Pretest:setvthrcompcaldel

This will avoid the abort. DACs can be saved as well. 

There is a reason that the pretest is not part of the fulltest. "In principle" it is designed to allow for weeding out bad modules before the long test starts. 

Please also make a short comment in hn. (I know the ETH position here, Andrey talked to me until I gave up... But it will help in the future to have the discussion in one place and to find it.) Many thanks. 

Cheers,
--U.

**Comment by ursl** [comment]
I am appalled by the lack of reaction in hn. 

I will not go beyond the latest commit in this issue. It will not go into a production release, I'd say. In case you need help, have a look at the twiki. Eventually I'll take the information out of there again. 

Good luck and make really sure that nobody ever screws up. Never.

Cheers,
--U.

**Comment by piberger** [comment]
We discussed again here at ETH today and and we think it's ok to keep it like in the production branch for normal qualification and use either manual pretest or the new flag if we want to look at the modules anyway. Thanks.
