### ISSUE TITLE
unphysical scurve thresholds when plateau not found

### ISSUE THREAD

**Issue by lantone** [psi46/pxar#428]
Hi,

We here in FPIX-land have been seeing some modules with damaged ROCs in which many pixels don't fire at Vcal=35 as needed to trim the module test.  In the Trim test, these pixels were returning VthrComp turn-on thresholds of ~50, but looking directly at the s-curves shows that these pixels never actually turn on.

The issue comes from this block of code:
https://github.com/psi46/pxar/blob/master/ana/PixInitFunc.cc#L262-L271

If a plateau is not found, jbin remains at -1 and breaks the subsequent algorithm.  In my local installation, I just set the resulting threshold to -1 and return from the function if the plateau is not found, which seems to fix the inconsistencies we had been seeing.

Should I let an official developer implement a solution or prepare a pull request with what I've done?

Thanks,

Jamie

**Comment by ursl** [comment]
Hi Jamie,

I'll fix this tomorrow.

Many thanks for the report.

Cheers,
--U.

Am Mittwoch, 24. Februar 2016 schrieb Jamie Antonelli :

**Comment by ursl** [comment]
Hi Jamie,

sorry I forgot to push yesterday. Can you please have a look whether
the master's head fixes your problem? Sorry, given the production
unstatus here I have no working module in hand to test myself.

Cheers,
--U.

**Comment by lantone** [comment]
Hi Urs,
I can confirm that your commit has fixed the problem we were seeing, thanks!
