### ISSUE TITLE
inconsisten tbmParameter file naming for L1 modules

### ISSUE THREAD

**Issue by werdmann** [psi46/pxar#429]
On start-up for an L1 module pxar reads tmbParameter_xx.dat with xx=C0a,C0b,C1a,C1b
When the save button is hit in the gui, it writes xx=C0a,C0b,C2a,C2b instead.

**Comment by ursl** [comment]
Hi Wolfram, 

can you try again with the master's head, please? 

Cheers,
--U.

**Comment by werdmann** [comment]
That fixes the problem. Thank you.

Wolfram
