### ISSUE TITLE
vsh is a 4 bit dac for proc600

### ISSUE THREAD

**Issue by werdmann** [psi46/pxar#444]

**Comment by simonspa** [comment]
Suggest to add an "new" DAC to core/utils/dictionaries.h :

```
 _registers["vsh600"] = dacConfig(ROC_DAC_Vsh,15,ROC_REG);
```

**Comment by ursl** [comment]
Hopefully fixed with https://github.com/psi46/pxar/commit/2d1449ac698bc9efc354ad00ca25596d1a186a26
