### ISSUE TITLE
DTB clock and pXar APIs ...

### ISSUE THREAD

**Issue by dinardo** [psi46/pxar#445]
Dear Experts,
I would like to use DTB with **external clock**.
I'm using the latest greatest FW (4.6) and latest greatest SW version (4.7).
Apparently the possibility to use an external clock is broken since sometime ago.
**(1)** Do you guys know when this feature will be put back in place ?

**(2)** I would like to use the API method to **stretch the clock**:
   setClockStretch(src, delay, width)

**(A)** Is this function working ?
**(B)** What the meaning of the three parameters ?
**(C)** What are the units of the three parameters ? seconds, milliseconds, etc ...

Many thanks for your help.
Kind regards,
- Mauro Dinardo.

**Comment by simonspa** [comment]
Hi @dinardo 

(1) It is broken since summer 2015 and Beat hasn't found the time to repair it. I won't bet on that happening before the detector is in.

(2) Not sure, never used it. Original author is @roberts42 in 6b4e1511222b4246de8d49113760a086fd1ba635

Cheers

**Comment by simonspa** [comment]
corresponding firmware method is here: https://github.com/psi46/pixel-dtb-firmware/blob/master/software/dtb_expert/pixel_dtb.cc#L407
Would be nice if you add the missing documentation once you found out how it works.
