### ISSUE TITLE
Issue with core/CMakeLists.txt

### ISSUE THREAD

**Issue by dinardo** [psi46/pxar#447]
It seems that the core/CMakeLists.txt is not able to retrieve the location of python includes when these are arbitrarily located in the operating system.

I think that to fix this, one should simply add the following line:
`include_directories(` $ENV{PYTHON_INCLUDE_DIR} )
or something similar calling the environment variable that points to the python includes.

That line should be put here:
https://github.com/psi46/pxar/blob/master/core/CMakeLists.txt#L93

I did it and it worked for me.

Let me know.
Kind regards,
- Mauro.

**Comment by ursl** [comment]
Is maybe fixed with https://github.com/psi46/pxar/commit/8d895441f5bc79a77beb701501b84b3855e79a1f

Feedback appreciated (even with a time constant of years)
