### ISSUE TITLE
PHOptimization flawed with current chip (PROC600v3)

### ISSUE THREAD

**Issue by stephbur** [psi46/pxar#448]
The current pulse height optimization routine often delivers vastly different values for scale and offset, even if run twice directly one after the other. Sometimes it fails completely and sets the scale and offset to 0, resulting in completely useless measurements.

This is most likely due to the routine picking pixels at random to serve as examples for upper and lower bounds. Since there is a known issue with  a very large spread in pulse height readout in the current ROC (mostly due to an offset), this leads to more or less arbitrary results. 

Unfortunately this is not really fixable in software, as the phscale and phoffset parameters are global parameters of the chip. Once the issue is fixed in hardware, the routine is expected to work well again.

**Comment by ursl** [comment]
Closed while waiting for new chips
