### ISSUE TITLE
Improve the timing scans for TBM10 (layer 1)

### ISSUE THREAD

**Issue by dkotlins** [psi46/pxar#450]
Improve timing scan for layer 1. Add diagnostics histograms. Make clear which timing scans work for TBM10 and which not.

Copy of my email:

1) In Pretest: findtiming 
usually works fine, that is it produces new settings for all TBM phases, but there is no diagnostics,
e.g. there are no histograms which would help to judge if the new settings are safe.

2) In Pretest: settiming 
Fails always for L1 modules. It says that timing are not write, than tries to find new ones but end 
with a message that no good timing exist. This happens even when the present settings are good.

3) In Timing: phasescan
This just runs for ever and never stops

4) In Timing: tbmphasescan
It works only when “no token pass” is selected. Otherwise it fails even if good settings are known.

5) In Timing: rocdelayscan
Always fails.

6) In Timing: timingtest:
Just says that timing are not good, even if they are good.

Some of these problems might be related to the tests not being updated for L1 dual-TBM modules.

What I would like to propose is that (1) makes some plots and that (2) runs even with token pass.
That is something similar to what we have in the XDAQ system at P5. I could work on this next week.
But I would still like to hear you comments & suggestions.

**Comment by ursl** [comment]
Hi Danek, 

PixTestTiming has been moved to moreTestParameters.dat. It is dated code that is not maintained by anybody anymore. Likely it will be removed. 

PixTestPretest::setTimings() is for TBM08A/TBM08B. Code has been added to make this clearer to the user via tool tips. Safeguards in the code make sure it is not called for the wrong TBM type. 

PixTestPretest::findTiming() is now based on Wolfram's code (which supersedes the code in setTimings()). It produces histograms showing some characteristics along the optimization process. 

Please re-open this issue (or a new one) in case of problems.
