### ISSUE TITLE
Implement the fix to configure modules with less noise. Urgent!

### ISSUE THREAD

**Issue by dkotlins** [psi46/pxar#451]
Implement the so called "software fix" to reduce the noise in layer 1 ROCs.
It makes sure that after each configuration the state of the TRIM/MASK register in each double-column is FFFF. One way to do it is to enable double-columns AFTER the pixel TRIM/MASK are programmed. Stephan B. and Hans-Christian know the details.
This fix should allow trimming of L1 modules down to VCAL=35 instead of 60.

**Comment by ursl** [comment]
The software fix is not possible. It would imply a firmware fix.
