### ISSUE TITLE
PH optimisation for PROC600

### ISSUE THREAD

**Issue by starodum** [psi46/pxar#452]
A new PH optimisation procedure required for PROC600V3(V4) that will be used for replacement L1 module production and qualification (the current algorithm basically fails for this chip). Backward compatibility with a psi46dig family is mandatory. 
Ideally the algorithm should be usable at P5 (for irradiated chips).

**Comment by ursl** [comment]
This was done in March, latest relevant commit https://github.com/psi46/pxar/commit/4d466eb370ffe611dc9f24e7ff49f16bd45677d7#diff-33e4164d30fef5a67fb5a8fdd7b1a1bd
